### PR TITLE
bugfix: add syntax error rule in github workflow using eslint

### PR DESCRIPTION
**Pull request by hawi19952**
## Description
This PR is a response to the open issue of [2167](https://github.com/bigskysoftware/htmx/issues/2167). 
The introduced changes targeted: 

1. List of dependencies
2. Test cases
3. GitHub CI workflow

The goal is to enforce checking for syntax errors on the CI workflow. 

As a side-effect, `estlint` caught  some syntax errors beyond the one introduced in the issue 2167, so I got them fixed. 

after fixing this issue, 7 of the tests were failing, and that might lead to the failure of the CI pipeline. 

## Checklist

* [x] I have read the contribution guidelines
* [x] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
  source changes)
* [x] This is either a bugfix, a documentation update, or a new feature that has been explicitly
  approved via an issue
* [x] I ran the test suite locally (`npm run test`) and verified that it succeeded

### CODE REVIEW

**Comment by Renerick** [comment]
Please retarget to dev

**Comment by alexpetros** [comment]
htmx 2.0 is going to have source linting, but we're not going to include it for the 1.0 branch. If you'd like to fix the big on its own without the other changes, we'd welcome that.

**Comment by hawi19952** [comment]
Thanks for highlighting that, most appreciated.

I'd truly be honored to get up to speed in your upcoming roadmap to collaborate effectively. Is it possible to direct me to where I can find it?

Thanks in advance.

**Comment by alexpetros** [comment]
Feel free to pop into the Discord and chat us up on #htmx-dev

**Pull request closed without merging**
