### PR TITLE
Add error messages

### PR DESCRIPTION
**Pull request by checketts**
These error messages will be included in the logError call now, so target selector details and similar will be exposed to the user.

### CODE REVIEW

**Comment by alexpetros** [comment]
I don't know... obviously more logging is good but on some level I think these are things you should only log if the developer explicitly asks for them. It makes sense to log the `historyCache` if you have a `historyCache` error, but not necessarily as standard behavior? That's sort of what the debugger is for.

@1cg thoughts?

**Comment by checketts** [comment]
This PR doesn't add any logging that wasn't already being logged. It merely ensures the details are present so the log message is useful.

**Comment by alexpetros** [comment]
Yeah I get that, but I think the expectation from users is that, by default, exceptions print their stack trace and that's it. I don't think it's really the library's place to decide to log a bunch of other runtime variables.

**Comment by 1cg** [comment]
We need to think hard about this: string constants blow out the size of the library.  Maybe we can make this an extension, e.g. `dev-messages` or something like that?

**Comment by checketts** [comment]
I agree with the concern around string constants. I'll remove the 'message' attributes and move them into an extension. 

The extension will merely be an event listener on the body that gives the detail log message. So it won't even need to leverage the `hx-ext` mechanism.

**Comment by alexpetros** [comment]
@checketts that sounds good to me. I'm going to close this PR, and feel free to open a PR on the core that hangs relevant data on the error object (but doesn't log it by default) as needed.

**Pull request closed without merging**
