### PR TITLE
htmx.js: Fix typo

### PR DESCRIPTION
**Pull request by cclauss**
## Description
*Please describe what changes you made, and why you feel they are necessary. Make sure to include
code examples, where applicable.*

Corresponding issue:

## Testing
*Please explain how you tested this change manually, and, if applicable, what new tests you added. If
you're making a change to just the website, you can omit this section.*

## Checklist

* [x] I have read the contribution guidelines
* [x] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
  source changes)
* [ ] This is either a bugfix, a documentation update, or a new feature that has been explicitly
  approved via an issue
* [ ] I ran the test suite locally (`npm run test`) and verified that it succeeded

### CODE REVIEW

**Comment by alexpetros** [comment]
Closing per contribution guidelines:

> Typo fixes in the documentation (not the code comments) are welcome, but formatting or debatable grammar changes will be automatically closed.

**Comment by cclauss** [comment]
% `python3 -m pip install codespell`
% `codespell --ignore-words-list=ans,doesnt,hda,nam --skip="*.json,./dist/htmx.min.js,./www/static/node_modules/*" `
```
./CHANGELOG.md:33: specifing ==> specifying
./test/ws-sse/server.mjs:147: visibile ==> visible
./test/attributes/hx-sse.js:64: arent ==> aren't
./test/lib/handlebars-v4.7.6.js:1044: condtional ==> conditional
./test/lib/handlebars-v4.7.6.js:2781: involed ==> involved
./test/lib/handlebars-v4.7.6.js:2824: statments ==> statements
./test/lib/handlebars-v4.7.6.js:2888: mulitple ==> multiple
./test/lib/handlebars-v4.7.6.js:2906: mulitple ==> multiple
./test/lib/handlebars-v4.7.6.js:2969: respnses ==> responses
./test/lib/morphdom-umd.js:71: efficently ==> efficiently
./test/lib/morphdom-umd.js:249: vise ==> vice
./test/lib/_hyperscript.js:164: carrage ==> carriage
./test/lib/_hyperscript.js:3647: emtpy ==> empty
./test/lib/_hyperscript.js:5682: intitial ==> initial
./test/lib/mustache.js:113: indendation ==> indentation
./dist/htmx.js:2107: superseeds ==> supersedes
./dist/ext/preload.js:117: WHhen ==> when
./www/content/essays/rest-copypasta.md:68: revered ==> reversed
./www/content/essays/two-approaches-to-decoupling.md:42: re-use ==> reuse
./www/content/posts/2023-09-22-htmx-1.9.6-is-released.md:15: specifing ==> specifying
./www/content/examples/active-search.md:113: Te ==> The, Be, We, To
./www/content/examples/active-search.md:125: varius ==> various
./www/content/examples/active-search.md:155: ridiculus ==> ridiculous
./www/content/examples/active-search.md:186: ridiculus ==> ridiculous
./www/content/examples/active-search.md:210: ridiculus ==> ridiculous
./www/static/test/ws-sse/server.mjs:147: visibile ==> visible
./www/static/test/attributes/hx-sse.js:64: arent ==> aren't
./www/static/test/lib/handlebars-v4.7.6.js:1044: condtional ==> conditional
./www/static/test/lib/handlebars-v4.7.6.js:2781: involed ==> involved
./www/static/test/lib/handlebars-v4.7.6.js:2824: statments ==> statements
./www/static/test/lib/handlebars-v4.7.6.js:2888: mulitple ==> multiple
./www/static/test/lib/handlebars-v4.7.6.js:2906: mulitple ==> multiple
./www/static/test/lib/handlebars-v4.7.6.js:2969: respnses ==> responses
./www/static/test/lib/morphdom-umd.js:71: efficently ==> efficiently
./www/static/test/lib/morphdom-umd.js:249: vise ==> vice
./www/static/test/lib/_hyperscript.js:164: carrage ==> carriage
./www/static/test/lib/_hyperscript.js:3647: emtpy ==> empty
./www/static/test/lib/_hyperscript.js:5682: intitial ==> initial
./www/static/test/lib/mustache.js:113: indendation ==> indentation
./www/static/src/htmx.js:2107: superseeds ==> supersedes
./www/static/src/ext/preload.js:117: WHhen ==> when
./www/themes/htmx-theme/highlighting/two-dark-edited.tmTheme:800: obejct ==> object
./www/themes/htmx-theme/highlighting/two-dark-edited.tmTheme:833: variabel ==> variable
./www/themes/htmx-theme/static/js/preload.js:117: WHhen ==> when
./www/themes/htmx-theme/static/js/htmx.js:2107: superseeds ==> supersedes
./src/htmx.js:2107: superseeds ==> supersedes
./src/htmx.js:3763: realiable ==> reliable
./src/htmx.js:3763: browswer ==> browser
./src/ext/preload.js:117: WHhen ==> when
49
```

**Comment by alexpetros** [comment]
Spellchecking code comments in `/www/static/test/lib/handlebars-v4.7.6.js:2906` is not a good use of your time, or ours.

**Comment by cclauss** [comment]
--skip="*.json,./dist/htmx.min.js,./www/static/node_modules/*,/www/static/test/lib/handlebars"

**Pull request closed without merging**
