### PR TITLE
feat: Improve web site accessibility/legibility

### PR DESCRIPTION
**Pull request by henrikvilhelmberglund**
## Description
*Please describe what changes you made, and why you feel they are necessary. Make sure to include
code examples, where applicable.*

This PR improves web site accessibility/legibility by adding alt attributes where needed, changing colors to improve contrast, changing the fake links in the logo to spans and adding an edited highlighting theme which makes the background color darker and comments brighter.

It also adds doctype and a meta description tag for SEO.

Feel free to edit the colors if needed.

Before: 
msedge-2023-12-09-15-13-msedge_OQKVUdyDyT

After:
msedge-2023-12-09-15-13-msedge_bkZYSBp74L

Lighthouse before:
 
brave-2023-12-09-16-03-brave_fSBeZETAcP

Lighthouse after (locally served):

brave-2023-12-09-16-03-brave_sW41HZE8b5

## Testing
*Please explain how you tested this change manually, and, if applicable, what new tests you added. If
you're making a change to just the website, you can omit this section.*

No tests added.

## Checklist

* [X] I have read the contribution guidelines
* [X] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
  source changes)
* [X] This is either a bugfix, a documentation update, or a new feature that has been explicitly
  approved via an issue
* [ ] I ran the test suite locally (`npm run test`) and verified that it succeeded

### CODE REVIEW

**Review by svenberkvens — COMMENTED** [review]
Don't have write access, but looks good to me!

**Review by dz4k — APPROVED** [review]

**Comment by fhp-mec** [comment]
Not sure the reasoning why, but @1cg likes quirks mode...
https://discord.com/channels/725789699527933952/974086000307499028/1178365725186994177

**Comment by henrikvilhelmberglund** [comment]
> Not sure the reasoning why, but @1cg likes quirks mode... https://discord.com/channels/725789699527933952/974086000307499028/1178365725186994177

Interesting, you can remove the doctype then!

**Review by alexpetros — APPROVED** [review]
These are great, thank you so much.

**Pull request merged**
