### PR TITLE
Actually pass original event on to `htmx:configRequest`

### PR DESCRIPTION
**Pull request by thomaseizinger**
Previously, we passed the _element_ as the original event. I think this bug was introduced in https://github.com/bigskysoftware/htmx/commit/8bb0399052f5a52a49e9e4f0f9624d25f1c2e890.

We can easily fix this by actually using both arguments of the `handler` closure.

Let me know if there is a better way to write this test.

### CODE REVIEW

**Comment by 1cg** [comment]
oosh, nasty bug, thank you for catching it

can you retarget to `dev` branch for me?

**Comment by thomaseizinger** [comment]
> can you retarget to `dev` branch for me?

Done.

**Comment by thomaseizinger** [comment]
Is anything blocking this from being merged @1cg?

**Comment by 1cg** [comment]
just time, laziness and intellectual ability ;)

**Pull request merged**
