### PR TITLE
Beautify file-upload-input.md

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Comment by alexpetros** [comment]
It's fine the way it is 👍

**Comment by gotcha** [comment]
The reason I submitted this PR is that I had trouble to read that page.

@alexpetros Is there anything wrong in making it more readable ?

**Comment by alexpetros** [comment]
The source change you made wouldn't change anything about how the page is rendered, because markdown linebreaks are not preserved in the HTML.

**Comment by gotcha** [comment]
@alexpetros 1) Regarding line feeds, are you telling me the rendering on the site is not in line with GH rendering ?

2) Did you see that I also changed casing and emphasized the form and input words with code ?

**Pull request closed without merging**
