### PR TITLE
End request lock when xmlHttpRequest is aborted

### PR DESCRIPTION
**Pull request by ChexWarrior**
This is a fix for the issue I raised in #224.  

I'm new to this code base so this is very much WIP, but I've added what I think addresses the main problem and welcome any feedback.

### CODE REVIEW

**Comment by 1cg** [comment]
looks good to me

is there a way to add a test?

**Comment by ChexWarrior** [comment]
Sure thing, I will look into creating a test!

**Comment by ChexWarrior** [comment]
@1cg Running into a slight issue with the tests. It seems Sinon doesn't like it when you abort an XMLHttpRequest before it sends.  Here is test I'm working on (in test/core/events.js):
```js
    it.only("htmx:beforeRequest continues to fire after aborting a request", function () {
        var counter = 0;
        var handler = htmx.on("htmx:beforeRequest", function (evt) {
            counter += 1;
            evt.detail.xhr.abort();
        });
        try {
            var div = make("<form hx-trigger='click' hx-post='/test'><input name='param' value='foo'></form>");
            div.click();
            div.click();
            should.equal(counter, 2);
        } finally {
            htmx.off("htmx:beforeRequest", handler);
        }
    });
```

The event handler is called with no issue on the first div.click(), however when the xhr goes to send within issueAjaxRequest Sinon throws an error in its verifyState method because the xhr object's readyState property is 0 instead of 1.  It seems that Sinon doesn't expect you to abort a request berfore sending it however this seems allowed on the actual browser implementation of XMLHttpRequest.  Does this seem like a bug in Sinon or should we add logic to prevent xhr.send() if the xhr has already been aborted?

**Comment by 1cg** [comment]
OK, might not be easily testable w/ sinon.

Would you mind looking at how hard it would be to add a manual test to the /test/manual directory for it and use the normal xhr support?

I run through those as well before releases manually to verify things are working.

**Comment by ChexWarrior** [comment]
I've added a test that is essentially the same as the minimal example I used in #224.  I've setup a beforeRequest event that adds a message to the target area's innerHTML, this message should continue to be appended even if a previous beforeRequest event canceled the current XMLHttpRequest.

**Pull request merged**
