### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by tunguski**
Just a proposal. Let me know what do you think.

### CODE REVIEW

**Comment by gnat** [comment]
I like the idea of supporting `@media (prefers-color-scheme: dark) {` for people who don't have something like Dark Reader installed.

The color selections here are a little over saturated, and the gradient should probably be removed, but the fundamental idea is sound.

**Comment by 1cg** [comment]
Sorry I let this sit so long.  I think I'd prefer a black background to blue for a dark mode.  Is that doable?  (my design-fu is awful, of course)

**Comment by alexpetros** [comment]
@tunguski unfortunately, we did a website refactor pretty recently and removed the `scss` files entirely. Are you interested in rebasing this PR against the current website build?

**Comment by gnat** [comment]
image

**Comment by gnat** [comment]
That's [Dark Reader](https://darkreader.org/) extension. I recommend it as an interim solution (..although I imagine most devs desiring lower brightness already are aware :wink:)

First impressions really do count.. so if we're "taking over" this responsibility, it has to look good (dark reader's design is good enough IMO). Everyone who has wanted to contribute a dark mode so far has "programmer art" design sensibilities (sorry OP, but it is a good idea!)



The site will get one eventually but short term I recommend dark reader extension. If it's a worse dark mode than dark reader, we need to avoid it.

**Pull request closed without merging**
