### PR TITLE
FIX: Scroll Event Throttling

### PR DESCRIPTION
**Pull request by benpate**
[As requested](https://github.com/bigskysoftware/htmx/issues/168#issuecomment-685244091), I'm moving this into its own PR.  

My apologies for the lack of tests.  I'm still trying to get my head around the testing tools that HTMX uses.  This did pass all of my manual tests.  In case it's helpful, I've posted my test page here: http://sseplaceholder.openfollow.org/scroll.html

### CODE REVIEW

**Comment by benpate** [comment]
In case it's helpful, I've posted a demo here -- http://sseplaceholder.openfollow.org/scroll.html

**Comment by 1cg** [comment]
This doesn't look super easily testable to me.  I do have manual tests that I (sometimes) remember to run before releases.  Take a look at `/tests/manual`

Maybe include your existing test in there?

Anyway, the change looks good.  I am going to merge it in the next day or so.

**Comment by benpate** [comment]
Thanks for merging this into dev.  I've just updated this pull request with a new manual test page that demonstrates the new scrolling behavior.  So, you may want to re-merge, so that the new test/demo is included. :)

**Comment by 1cg** [comment]
@benpate moved the polling interval inside the conditional, so we aren't setting it up every time `initScrollHandler()` is called:

https://github.com/bigskysoftware/htmx/commit/5f300f1bbca867cb7455e4ee802cf98dea430d25

**Comment by benpate** [comment]
Good catch. Thank you!

**Comment by o-o-o-o-o** [comment]
Instead of scroll throttling, would it make more sense to use [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)?

**Comment by benpate** [comment]
This is a great suggestion. I did not know about this API, and on first glance, it would make sense to use it. 

From the article you linked, it looks like it is not supported by IE, which is a current browser target for HTMX. 

We might consider a parallel implementation for newer browsers, but that might cause maintainability headaches down the road. 

I'll defer to @1cg on browser support issues. But, let me know if (and how) you'd like to implement this API, and I'm happy to take a crack at it.

**Comment by 1cg** [comment]
We are targeting IE11 for now.  I don't see a lot of perf complaints around the revealed stuff, but if I do I'll consider a separate IE11 code path.

**Pull request merged**
