### PR TITLE
Allow explicitly opting-out from an inherited hx-select

### LINKED ISSUE #442: How to have a child element opt out of a parent's `hx-select`
I was hoping I could just write `hx-select=""` on the child to have it opt-out of `hx-select` functionality and use the full result of its `hx-get`, but it seems that `maybeSelectFromResponse` only stops searching when the value of `hx-select` is truthy, rather than non-null, so `hx-select=""` gets ignored entirely.

(Rigjt now I'm working around this by setting `hx-select="#id-of-root-element-of-response"` on the child element, basically turning `hx-select` into a no-op.)

Currently what happens is `getClosestMatch` only stops traversing for when it gets truthy value: https://github.com/bigskysoftware/htmx/blob/6f8899f6fddf0bcf4770eb5387597e9afb578cb5/src/htmx.js#L109-L111

it's called by `getClosestAttributeValue`, which passes `getClosestMatch` the attribute value itself (instead of say a bool): https://github.com/bigskysoftware/htmx/blob/6f8899f6fddf0bcf4770eb5387597e9afb578cb5/src/htmx.js#L119-L125

which is called by `maybeSelectFromResponse`: https://github.com/bigskysoftware/htmx/blob/6f8899f6fddf0bcf4770eb5387597e9afb578cb5/src/htmx.js#L635-L637

I think this could be solved by changing `getClosestAttributeValue` to stop traversing when it reaches a non-null attribute value:
```diff
 function getClosestAttributeValue(elt, attributeName) { 
     var closestAttr = null; 
     getClosestMatch(elt, function (e) { 
-        return closestAttr = getAttributeValue(e, attributeName); 
+        closestAttr = getAttributeValue(e, attributeName); 
+        return closestAttr != null;
     }); 
     return closestAttr; 
 } 
```

Does this sound like a reasonable change/am I going about my issue wrong?

### PR DESCRIPTION
**Pull request by angusholder**
Fixes #442

### CODE REVIEW

**Comment by 1cg** [comment]
@angusholder thoughts on :point_up:

**Comment by angusholder** [comment]
I think you're right, it's not very clear, although I think `none` sounds confusing too - what about borrowing from the [CSS keywords for controlling inheritance](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#controlling_inheritance) and going with `hx-select="unset"`?

**Comment by 1cg** [comment]
this is why I ask smart people questions

unset is perfect

want to update the PR?

**Comment by angusholder** [comment]
Okay nice! I'll go update the PR another day

**Comment by 1cg** [comment]
still very interested in this idea

**Comment by 1cg** [comment]
hi there, still interested in pursuing this w/ the `unset` modifier...  lmk if you have time for it...

**Comment by 1cg** [comment]
ping...

**Comment by 1cg** [comment]
the `unset` option has been implemented in htmx

**Comment by bblanchon** [comment]
@1cg, please add it to [the documentation](https://htmx.org/attributes/hx-select/).

**Comment by angusholder** [comment]
> the `unset` option has been implemented in htmx

Sorry I didn't end up finishing this, thanks a lot for adding it!

**Pull request closed without merging**
