### PR TITLE
FEATURE: Limit number of child elements in hx-swap

### PR DESCRIPTION
**Pull request by benpate**
This pull request partially addresses #130 by adding an optional `limit:` argument to the `hx-swap` attribute.  It looks at where new nodes are being added into the DOM, and removed nodes from the opposite end.  So, since `hx-swap="afterbegin"` adds new elements to the top of the node's list of children, `hx-swap="afterbegin limit:10"` will remove elements from the bottom of the node's list of children until there are only ten.

I think there may be more work to do here, and will continue that discussion in the original issue #130.

Along the way, this code also addresses a minor bug in the `maybeReveal` function that can crash if the user scrolls too quickly.  We address this by double checking that nodes have been initialized before allowing the "reveal" trigger to continue.

### CODE REVIEW

**Comment by 1cg** [comment]
Finally getting a chance to look at this.  Code looks good, but I notice some code related to scrolling in here.  Did two branches cross pollute?

**Comment by benpate** [comment]
Honestly, this was an interesting idea, but I think I'd scrap it, now.  Though it works well enough on its own, it would really need more work to be actually useful.  For instance, I started working on a previous/next mechanism so that when items were added to the top/bottom of a container we could still scroll back to the original position.  I think most of the discussion happened in issue #130, if you want to refresh your memory.

It's a pretty cool enhancement to infinite scrolling, and I'm happy to take another shot at it, but it feels incomplete to me as it is, and we should get some architectural guidance from @1cg before we put too much more time into it.

**Comment by 1cg** [comment]
Roger, I'll close it for now and we can revisit after you are world famous with the preload extension...

**Comment by benpate** [comment]
Not sure I want to be world famous, but if it does happen, I promise to give you a guest spot on my podcast:  "The @benpate experience"

**Pull request closed without merging**
