### PR TITLE
HX-Redirect causing indicators to clear before redirect

### PR DESCRIPTION
**Pull request by webdevcody**
not sure if this would break stuff, but I was seeing issues with the indicators clearing before the redirect finished.  See video for issue.

https://github.com/user-attachments/assets/a24f750b-285e-4394-b66d-9183dc8a7e87

### CODE REVIEW

**Comment by Telroshan** [comment]
Hey, seems you'll want to run `npm format` to properly lint your code.

Other than that, I'm wondering what this `pageshow` event handling is about, is it necessary in this case? What issue does it solve?

**Comment by webdevcody** [comment]
@Telroshan Here is the issue without the pageshow


https://github.com/user-attachments/assets/a97d7af3-ade4-4ca5-9b8c-07d3da9c4912

**Comment by jadamita** [comment]
> @Telroshan Here is the issue without the pageshow. Basically the browser is going to cache the state of the previous page, so since we do not ever re-enable the button or hide the indicator, it'll show when the user clicks back.
> 
>  pageshow.mp4

off topic, but what software was used for that recording? it's buttery smooth.

**Comment by JonathanFajobi** [comment]
@jadamita

https://www.screen.studio/

**Comment by 1cg** [comment]
i think I already implemented this, based on @webdevcody's feedback, thank you!

**Pull request closed without merging**
