### PR TITLE
Avoid: "Element.querySelector: '...' is not a valid selector"

### PR DESCRIPTION
**Pull request by deveil**
When hx-get swap for an xml page (inkscape svg for exemple) with namespaces on elements, htmx failed.
This trick avoid the error raised.

### CODE REVIEW

**Comment by 1cg** [comment]
Would you  mind adding a test demostrating this issue, and retargeting to `dev`?

**Comment by deveil** [comment]
I need to see how unit tests are performed in your repository to take
examples.
I will try to do that, perhaps next week or later.

**Comment by 1cg** [comment]
Can you retarget this to the `dev` branch?

**Comment by alexpetros** [comment]
Hi @deveil, sorry that this has been sitting for a bit. If you can perform the following updates I'll get it looked at ASAP:
* Rebase against the current dev branch
* Explain exactly what your "trick" does, because we it's not obvious and we will probably want to document what's broken exactly.

**Comment by alexpetros** [comment]
Feel free to reopen if you're still interested.

**Pull request closed without merging**
