### PR TITLE
Add missing } in core ajax tests

### PR DESCRIPTION
**Pull request by rbri**
Found while working on improving the js support of HtmlUnit.

### CODE REVIEW

**Comment by rbri** [comment]
Looks like this reduces the number of test in the test suite. After fixing that the 1.9.7 release test suite changed from 584 to 653 tests.

**Comment by alexpetros** [comment]
Huh, odd, thanks. Can you rebase against `dev` please?

**Comment by alexpetros** [comment]
Yes, the PR should be against the `dev` branch

**Comment by rbri** [comment]
So i have to create a new one...

**Comment by alexpetros** [comment]
Nope, you can retarget this PR!

**Comment by rbri** [comment]
like this?

**Comment by alexpetros** [comment]
Yup, but now you have to rebase it against dev so it's only the one commit

**Comment by rbri** [comment]
Sorry but i will create a new PR.

**Comment by rbri** [comment]
replaced by https://github.com/bigskysoftware/htmx/pull/1998

**Pull request closed without merging**
