### PR TITLE
Minor sytles fixes

### PR DESCRIPTION
**Pull request by constantinjoly**
These are some very minor style fixes suggestions for HTMX website seen on #141 

Website horizontal scrollbar
Content horizontal overflow on docs page
Menu adjustments (items spacing, alignment and responsive)
Content adjustements (sidebar and content block spacing and alignment)
Added a position sticky to sidebar nav on docs page.

I tried to use less code as possible without modifying the structure (except in menu for the github button).

If you find something wrong, please just let me know, I will correct it quickly.

### CODE REVIEW

**Comment by 1cg** [comment]
Thank you!

There are some other files in this pull request outside the side/styling.  Can you make sure you are up to date with `dev` and resubmit?  (If not I can tease out the stuff you changed I think.)

**Comment by constantinjoly** [comment]
Hm sorry, I'm not yet very confortable with git :( 
This is my first fork and pull request.

What I did is:
Fork and clone HTMX, create a branch "style-fix", commit some works, push to my github and ask a PR on your dev branch. 

I will search on google what I miss in the process. Any advice is welcome ;-)

**Comment by 1cg** [comment]
I ended up applying this change via a patch, to avoid the other changes that were coming in.

Can you do a fresh fork of the project and then do any additional work you'd like in the `dev` branch?

Thank you, by the way, the changes look great!

**Comment by constantinjoly** [comment]
Yes, ok, I will do this. Thank you for your comment ;-)

**Pull request closed without merging**
