### PR TITLE
Fix TypeError on null path variable

### PR DESCRIPTION
**Pull request by youssame**
## Description
I check if the `path` is null or empty when the user hasn't set the action property or has left it empty.

Corresponding issue: #2963

## Testing
I added two tests that check if everything is OK in two cases (action is unset or is empty)

## Checklist

* [x] I have read the contribution guidelines
* [x] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
  source changes)
* [x] This is either a bugfix, a documentation update, or a new feature that has been explicitly
  approved via an issue
* [x] I ran the test suite locally (`npm run test`) and verified that it succeeded

### CODE REVIEW

**Review by Telroshan — APPROVED** [review]

**Comment by Telroshan** [comment]
Bruh this online-retarget never seems to work as it should
My bad, forgot to check the target branch before approving the code change.
@youssame could you rebase against `dev` for source code changes as per the [contribution guidelines](https://github.com/bigskysoftware/htmx/blob/master/CONTRIBUTING.md) ? Thanks!

**Comment by youssame** [comment]
> Bruh this online-retarget never seems to work as it should My bad, forgot to check the target branch before approving the code change. @youssame could you rebase against `dev` for source code changes as per the [contribution guidelines](https://github.com/bigskysoftware/htmx/blob/master/CONTRIBUTING.md) ? Thanks!

My bad, done :)

**Comment by Telroshan** [comment]
Seems you'll want to rebase @youssame as the PR now brings a few unrelated commits in, making the diff harder to review

**Comment by youssame** [comment]
I just created a new PR #2967 that will be easier I will close this one

**Comment by youssame** [comment]
=> #2967

**Pull request closed without merging**
