### PR TITLE
Minor edits to article

### PR DESCRIPTION
**Pull request by bencroker**
Just a few minor edits and improvements to an otherwise great article.

### CODE REVIEW

**Comment by alexpetros** [comment]
I know this is well-intentioned but we can't open the door on non-typographical edits to essays. There's a million ways to write something, and if the authors of essays (by which I mean, at this time, the one guy who writes all the essays) want structural feedback they'll ask for it. Otherwise we'd have people PRing "hey this sentence would work better this way" all the time.

**Comment by bencroker** [comment]
If you say so.

**Comment by bencroker** [comment]
I used to frequently give @1cg feedback on essays “in the beginning”, in the hopes of improving quality and readability, but I guess things have changed. You’re also right that, in this case, the (unsolicited) changes I proposed are based on stylistic preference rather than grammatical fixes.

**Comment by alexpetros** [comment]
For sure, and I know you're not just some rando, I'm just doing my best to triage the decisions we have the bandwidth to make. I just know I personally wouldn't want to be thinking about word choice on a 6 week old essay unless there was some egregious error.

**Pull request closed without merging**
