### PR TITLE
5xx-style wildcard support for response-targets extension

### PR DESCRIPTION
**Pull request by siefca**
See https://github.com/bigskysoftware/htmx/issues/1564

With this change it is possible to use custom wildards, so for example `hx-target-4xx` will match 404 response status code.

### CODE REVIEW

**Comment by alexpetros** [comment]
Two concerns about this PR:

* I would like to give @spiffytech the opportunity to contribute since they are the one that originally raise the issue (if they're interested)
* We do not need custom wild cards. They add a lot of complexity to the extension for questionable value. I'd rather just see `x` made available as an alternative to `*` i.e. `5xx` instead of `5**`.

**Comment by spiffytech** [comment]
> I would like to give @spiffytech the opportunity to contribute since they are the one that originally raised the issue, and they said they'd be interested. Obviously it's open source, and they may not have the time, but I would like to give them more than 2 days.

Thank you :heart: I plan to tackle this tomorrow.

**Comment by siefca** [comment]
@alexpetros Ah, sorry, I misread the response and thought @spiffytech wants this feature badly, not wants to add the feature – my mind didn't associate "PRing" with "making a pull request" and I thought it meant that someone is very interested. :) lol. That's probably because I was beaten with hypermedia hrefs when I was little.

**Comment by alexpetros** [comment]
Very much appreciate you opening it @siefca! From the maintainer side, we're going to keep getting better at signposting what issues people should jump on. Closing now in favor a much smaller-scoped PR.

**Pull request closed without merging**
