### PR TITLE
[bug] Handle missing selectors for closest/find/next/previous

### PR DESCRIPTION
**Pull request by MichaelWest22**
## Description
when using some of the custom selector modes like find etc it now wraps the response in an array.  But when there happens to be no elements found it then wraps the null which will throw exceptions up the chain so we need to get it to return empty array instead.

Corresponding issue:
#2913 

## Testing
Added test and did manual testing to confirm find etc does not throw errors anymore when no elements are found

## Checklist

* [x] I have read the contribution guidelines
* [x] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
  source changes)
* [x] This is either a bugfix, a documentation update, or a new feature that has been explicitly
  approved via an issue
* [x] I ran the test suite locally (`npm run test`) and verified that it succeeded

### CODE REVIEW

**Review by Telroshan — APPROVED** [review]
Nice, simple & effective fix!

**Comment by MichaelWest22** [comment]
If we merge in #2902 first then this PR would need to be updated to use `result.push(...toNodeArray(xxxx))`

**Comment by MichaelWest22** [comment]
actually to merge this fix into #2902 you can simplify it down to this:
```javascript
let item
      if (selector.indexOf('closest ') === 0) {
        item = closest(asElement(elt), normalizeSelector(selector.substr(8)))
      } else if (selector.indexOf('find ') === 0) {
        item = find(asParentNode(elt), normalizeSelector(selector.substr(5)))
      } else if (selector === 'next' || selector === 'nextElementSibling') {
        item = asElement(elt).nextElementSibling
      } else if (selector.indexOf('next ') === 0) {
        item = scanForwardQuery(elt, normalizeSelector(selector.substr(5)), !!global)
      } else if (selector === 'previous' || selector === 'previousElementSibling') {
        item = asElement(elt).previousElementSibling
      } else if (selector.indexOf('previous ') === 0) {
        item = scanBackwardsQuery(elt, normalizeSelector(selector.substr(9)), !!global)
      } else if (selector === 'document') {
        item = document
      } else if (selector === 'window') {
        item = window
      } else if (selector === 'body') {
        item = document.body
      } else if (selector === 'root') {
        item = getRootNode(elt, !!global)
      } else {
        // Push back the unaltered string part, so that the standard selector fallback uses the exact initial string
        unprocessedParts.push(selector)
      }
      item && result.push(item)
```
Where you change it from pushing to the array each time to assign to a let variable and then only push at the end if item is not null or undefined which handles the null case well.

**Comment by Telroshan** [comment]
Yep makes sense @MichaelWest22 
Given that #2902 already generates a diff on all lines of that function, I think I'll directly embed your fix in here as I don't expect it to make reviewing any harder

**Comment by Telroshan** [comment]
Merged your changes in #2902, closing this one!

**Pull request closed without merging**
