### PR TITLE
Add delete option for hx-swap

### PR DESCRIPTION
**Pull request by ajusa**
See #645 for motivation.

This is my first contribution, so let me know if this is incorrect or missing some other case.

### CODE REVIEW

**Comment by 1cg** [comment]
implementation looks good, but now we need tests and docs :)

tests probably in 

test/attributes/hx-swap.js

and 

test/attributes/hx-swap-oob.js

and docs in

www/docs.md

and 

www/attributes/hx-swap.md

**Comment by 1cg** [comment]
Can you add tests for this swap style?

**Comment by ajusa** [comment]
Added tests and a quick mention in the docs. It's been a while since I've made a PR to a project of this size, please let me know if there are any additional steps I should take, especially with regards to Git. I've changed the branch to be dev as well and merged that into my fork, so it shouldn't have any conflicts as of now.

**Comment by ajusa** [comment]
Finally fixed the rebase issue I was running into, the git diff should be sensible now. Tests that I added pass as well. Let me know any additional documentation or tests to add. Shouldn't take long now that I know how to do it

**Comment by 1cg** [comment]
:crown:

**Pull request merged**
