### PR TITLE
Added webpack installation to docs

### LINKED ISSUE #755: How to import HTMX variable?
Hi guys!

I am using HTMX attributes on some dynamically generated DOM elements. HTMX is not working, as stated in the docs under third-party-packages unless you call htmx.process().

When I tried to call this, I get - correctly - the error:

> Uncaught ReferenceError: htmx is not defined

Any idea how I can import this htmx variable? No idea how the example in the docs can work.

Thx!

### PR DESCRIPTION
**Pull request by GitRon**
@1cg fixes #755

### CODE REVIEW

**Comment by GitRon** [comment]
@1cg what do you think about my change? 🙂

**Comment by 1cg** [comment]
Hey Ron, I'm working on open source stuff today, so I will take a look.

Sorry about the delay.

Thanks,
Carson

/// big sky software ///

------- Original Message -------

**Comment by GitRon** [comment]
No worries! Just wanted to aviod that it's getting lost

**Comment by 1cg** [comment]
merged, thank you!

**Comment by GitRon** [comment]
Thx!

**Pull request merged**
