### PR TITLE
docs: update jetbrains sponsor logo

### PR DESCRIPTION
**Pull request by niklas-wortmann**
## Description

We from JetBrains have a new logo for all JetBrains IDEs. We use the same logo on our website too https://www.jetbrains.com/ides/

### CODE REVIEW

**Comment by 1cg** [comment]
hi @niklas-wortmann can you also add an svg for the new darkmode as well?

**Comment by 1cg** [comment]
@niklas-wortmann checking in on this again, would love to get this updated

**Comment by niklas-wortmann** [comment]
Thanks for the ping, I should get to it latest by the end of the week. Sorry for that

**Comment by alexpetros** [comment]
Alrighty, thank you for the update!

**Review by alexpetros — APPROVED** [review]

**Pull request merged**
