### PR TITLE
Introduce consistent footer for all pages

### PR DESCRIPTION
**Pull request by tunguski**
This is only a proposal. Do not hesitate to reject it without doubts if you do not like it!

Initial version contains haiku and links from menu. Links in footer make it easier to navigate when scrolling close to the end on long and very long pages.

Additional tweaks:

* Remove column left padding for first column in row. It was commented in my previous PR, here it was problematic too.
* Slightly changed left/right margin on small screens.
* Remove `nav` class added to navbar only in some pages. It made navbar inconsistent in style between pages.

### CODE REVIEW

**Comment by tunguski** [comment]
# Screenshots (Firefox)

## Main

footer_main

## Reference

footer_reference

## Examples

footer_examples

**Comment by tunguski** [comment]
## Far heading experiment with bars

footer_with_bars

**Comment by tunguski** [comment]
# Footer comparison

footer_comparison

# Fixed margin for first column

fixed_first_column_margin

# Fixed menu height on examples page

menu_on_examples_page

**Comment by 1cg** [comment]
thank you looks great!

**Pull request merged**
