### PR TITLE
Add htmx/elem-go server examples

### PR DESCRIPTION
**Pull request by chasefleming**
`elem-go` is an HTML generation library written in Go that offers an integration with `htmx`. More information about this integration can be found in the `elem-go` documentation: [HTMX Integration](https://github.com/chasefleming/elem-go/blob/main/HTMX_INTEGRATION.md).

This PR that includes two example applications showcasing the combined use of `htmx` and `elem-go`:

1. **Counter Example**: Showcases a simple counter that can be incremented interactively.
2. **Todo List Example**: Demonstrates a dynamic todo list where tasks can be added and marked as complete or active.

Thanks!

### CODE REVIEW

**Comment by alexpetros** [comment]
Looks good, can you move it below tmpl please?

**Comment by chasefleming** [comment]
Sure thing @alexpetros . Put it there originally just so it was sorted alphabetically. PR updated.

**Comment by alexpetros** [comment]
No problem at all, and thank you!

**Review by alexpetros — APPROVED** [review]

**Comment by chasefleming** [comment]
Thanks @alexpetros !

**Pull request merged**
