### PR TITLE
feat(ext): add disable-element extension

### PR DESCRIPTION
**Pull request by David-Guillot**
Credits for the idea and the feature code go to @alexsemerad, the author of [the original PR](https://github.com/bigskysoftware/htmx/pull/812) for this extension. Mine is just adding tests and documentation.

### CODE REVIEW

**Comment by alexsemerad** [comment]
I just had a quick peak and the documentation. Everything is perfect, but there is one small detail. 

In the documentation, specifically in the "_Nominal case: disabling the element triggering the request_", you pass "**self**" to hx-disable-element, although I think it should've been "**this**" to disable the element triggering the event (according to the source code, see below):

```
    let elt = evt.detail.elt;
    let target = elt.getAttribute("hx-disable-element");
    let targetElement = (target == "this") ? elt : document.querySelector(target);
```

You have the option to replace "this" by "self" in the source code or change it in the documentation. I have to admit, "self" might indeed be more clear than "this". 

Again, awesome job and thanks!

**Comment by Renerick** [comment]
Great PR, but isn't this feature already implemented in https://htmx.org/extensions/loading-states/ (`data-loading-disable`)?

**Comment by 1cg** [comment]
Does seem like a bit of a dupe, but I'm fine with multiple extensions.  jQuery had loads of overlapping extensions, and that's the inspiration here.  @David-Guillot can you address @alexsemerad 's concerns?

**Comment by David-Guillot** [comment]
Thanks @alexsemerad for your attention on the `self` vs `this` matter. I wrote the documentation after taking care of the code, and `self` came to me naturally. So I'll change the code.

And thanks @Renerick for pointing `loading-states`, I didn't see it before taking over this new `disable-element` extension. Since @1cg agrees to have overlapping extensions, I'll go with keeping this PR open, as this new extension is more lean than `loading-states`.

**Comment by David-Guillot** [comment]
Here we go, I just added a fixup commit. Let me know if you're fine with it :wink:

**Pull request merged**
