### PR TITLE
Add configuration options list to reference docs

### PR DESCRIPTION
**Pull request by infogulch**
Could not figure out how to import directly from docs.md with zola.

### CODE REVIEW

**Comment by alexpetros** [comment]
Why do we need to duplicate—can we just link?

**Comment by infogulch** [comment]
That seems fine to me. I guess we'd want the docs page to link to the reference page?

**Comment by alexpetros** [comment]
I guess so, I don't really have a strong opinion. I'd default to linking to the new place, from the old place. We can always change it later.

**Comment by 1cg** [comment]
hold on there has to be a way to include stuff

**Comment by 1cg** [comment]
looks like the templates are based on Jinja2:

https://www.kytta.dev/blog/one-week-with-zola/

so 

```
{% include 'whatever' %}
```
should work maybe?

**Comment by infogulch** [comment]
> hold on there has to be a way to include stuff

I thought so too, but I couldn't figure it out.

`include` doesn't work, and I tried the get_section api too, but neither are parsed as template content.

image

https://www.getzola.org/documentation/templates/pages-sections/

https://www.getzola.org/documentation/templates/overview/#get-section

I guess because only files in the templates directory are invoked as template content.

> All templates live in the templates directory.

**Comment by 1cg** [comment]
well gosh darn it

**Comment by alexpetros** [comment]
@1cg I'm fine with the link as it's done here, let me know if you have any objections.

**Review by alexpetros — APPROVED** [review]

**Comment by alexpetros** [comment]
@infogulch do you mind rebasing? Sorry, there were a couple outstanding doc PRs.

**Comment by infogulch** [comment]
Done!

**Comment by alexpetros** [comment]
By the way I was looking for the config options a couple days ago, went to reference, and thought "why the hell aren't the config options here."

**Comment by infogulch** [comment]
Exactly! So I mentioned it on discord and immediately got waylaid by the "you reported it, you fix it" rule. Talk about shooting the messenger...

**Comment by alexpetros** [comment]
no good deed goes unpunished 🧙‍♀️

**Pull request merged**
