### PR TITLE
Add events support for WebSockets

### PR DESCRIPTION
**Pull request by Renerick**
Implements events support as per #1110

### CODE REVIEW

**Comment by 1cg** [comment]
@Renerick is this a breaking change (hard to tell from the diff).

Want to make sure it is properly documented if so...

**Comment by Renerick** [comment]
The only thing that is not backwards compatible is internal data of the extension (the socket object and the queue). But it's internal, undocumented, so nobody should have relied on it anyway. Also, reconnection implementation has been reworked, but it's also internal to the extension.

Other then that, the extension works exactly as before, except now it has events

I also want to look into the possibility to unit test websockets, but it's really tricky.

I will provide detailed changelog when I finish testing.

**Comment by 1cg** [comment]
you are a prince among men @Renerick

**Comment by 1cg** [comment]
@Renerick checking in on this.  I am planning a 1.8.5 release next week, just as an fyi.  No pressure, but wanted to let you know.

**Comment by Renerick** [comment]
@1cg Understood! I had plans to get back to this issue this weekend, so hopefully I'll manage to squeeze it into the release

**Comment by Renerick** [comment]
So here is the gist of what was done:

- new events for websockets
  - `htmx:wsClose`
  - `htmx:wsOpen`
  - `htmx:wsError`
  - `htmx:wsConfigSend`
  - `htmx:wsBeforeSend`
  - `htmx:wsAfterSend`
- WebSocket is exposed to event handlers via new wrapper object that allows to send additional messages through the same socket and to manipulate the message queue
  - Said wrapper holds the socket, the message queue and implementation of reconnection mechanism.
  - Hopefully, this will increase maintainability and simplify further development of the extension in light of incoming htmx 2.0
- WebSocket extension is now covered with unit tests
  - I introduced a websocket mocking library https://github.com/thoov/mock-socket
  - Test suit covers connecting, disconnecting, sending messages, receiving messages, as well as events.

No breaking changes, all attributes use the same syntax and logic as before.

Event details are in the docs https://deploy-preview-1126--htmx.netlify.app/extensions/web-sockets/

**Comment by 1cg** [comment]
🎉 thank you @Renerick awesome work as always!  great to see so many tests!

**Pull request merged**
